<!ELEMENT liga (jornada+)>
        <!ELEMENT jornada (partido+)>

        <!ELEMENT partido (local, visitante, estadio?)>
        <!ATTLIST partido
                id ID #REQUIRED>

        <!ELEMENT local (nombre, goles, estadisticas?)>
        <!ELEMENT visitante (nombre, goles, estadisticas?)>

        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT goles (#PCDATA)>
        <!ELEMENT estadio (#PCDATA)>

        <!ELEMENT estadisticas (falta | tiro | tarjeta)*>
        <!ELEMENT falta (#PCDATA)>
        <!ELEMENT tiro (#PCDATA)>
        <!ELEMENT tarjeta (#PCDATA)>